import { snippet } from './build-topic.mjs';

export const m18Topics = {
  'strict-compiler-flags': {
    hook: '**`strict`: true** enables strictNullChecks, noImplicitAny, strictFunctionTypes, and more. Senior engineers explain each flag and how they differ from C# NRT (compile-time only).',
    whatIs: '**strict** bundle turns on ~7 options including strictNullChecks, noImplicitAny, strictPropertyInitialization, useUnknownInCatchVariables. Enable individually for migration. strictNullChecks makes null/undefined explicit. Unlike C# NRT — no runtime enforcement.',
    glossary: [
      { term: 'strictNullChecks', longForm: 'null safety', plainDefinition: 'null/undefined not assignable without union.', example: 'string ≠ string|null' },
      { term: 'noImplicitAny', longForm: 'ban implicit any', plainDefinition: 'Untyped params error.', example: 'function f(x) // error' },
      { term: 'strictFunctionTypes', longForm: 'callback safety', plainDefinition: 'Contravariant param checking.', example: 'handler assignability' },
      { term: 'strictPropertyInitialization', longForm: 'class fields', plainDefinition: 'Fields init in ctor or definite assignment.', example: 'name!: string' },
    ],
    whyMatters: 'strict false accumulates any/null bugs. FAANG enforces strict. C# devs need validation at boundaries despite compile checks.',
    tipTitle: 'Interview trap: strict = runtime',
    tipBody: 'strictNullChecks does not stop JSON null at runtime.',
    steps: [{ title: 'strict true new projects', body: '' }, { title: 'migrate per-flag', body: 'strictNullChecks first' }, { title: 'fix with guards', body: 'unknown boundaries' }, { title: 'CI tsc', body: 'enforce' }],
    diagramTitle: 'strict family',
    diagram: 'flowchart TD\n  S[strict] --> N[noImplicitAny]\n  S --> NS[strictNullChecks]\n  S --> SF[strictFunctionTypes]\n  S --> U[useUnknownInCatchVariables]',
    snippets: [
      snippet('json', 'strict tsconfig', '{\n  "compilerOptions": {\n    "strict": true,\n    "noUncheckedIndexedAccess": true\n  }\n}', 'strict + extra flags.'),
      snippet('typescript', 'strictNullChecks', 'function greet(n: string) { return n.toUpperCase(); }\nconst x: string | null = get();\nif (x !== null) greet(x);', 'Narrow null before use.'),
      snippet('typescript', 'noImplicitAny', 'function process(data: unknown) {\n  if (typeof data === "string") return data.length;\n  throw new Error();\n}', 'unknown not implicit any.'),
      snippet('typescript', 'Failure: strict false', 'function parse(x) { return JSON.parse(x); } // any chain', 'implicit any poisons inference.'),
    ],
    compareRows: [['', 'TS strict', 'runtime', 'C# NRT'], ['null', 'compile union', 'JSON still null', 'warnings']],
    mistakesBody: '@ts-ignore everywhere. disable strict whole monorepo. assume NRT parity.',
    seniorProse: 'noUncheckedIndexedAccess high value. exactOptionalPropertyTypes for mature teams. document baseline tsconfig.',
    seniorRows: [['strict true', 'standard', 'migration cost'], ['per-flag', 'gradual', 'long intermediate']],
    seniorWarning: 'strict prevents runtime null. cannot name flags.',
    interviewTakeaways: ['strict ~7 options.', 'strictNullChecks compile-only.', 'noImplicitAny stops any.', '60s: strict bundle. validate boundaries. per-flag migrate. C# NRT similar warning only.', 'Follow-up: noUncheckedIndexedAccess.'],
    commonPitfalls: ['Weak: strict+any via ignore.', 'Weak: strictNullChecks validates JSON.', 'Strong: "strict family. compile-only. guards at boundary."'],
    relatedTopicIds: ['typescript-07-strict-null-checks', 'typescript-17-eslint-type-aware', 'typescript-17-ci-typecheck-pipelines'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'no types', note: 'JS no strict.', futureTopicSlug: 'javascript/types/versus-typescript' }, { language: 'typescript', concept: 'NRT', note: 'C# compile warnings.', futureTopicSlug: 'csharp/nullable/nrt' }],
    officialSources: [{ title: 'TS strict', url: 'https://www.typescriptlang.org/tsconfig#strict' }],
    animationHint: 'compare',
  },
  'isolated-modules-verbatim': {
    hook: '**isolatedModules** ensures per-file transpile for Babel/esbuild. **verbatimModuleSyntax** forces `import type` — TS 5+ clean emit.',
    whatIs: 'isolatedModules forbids cross-file const enum inline etc. verbatimModuleSyntax requires type imports use **import type**. Pair moduleResolution bundler for Vite. const enum problematic with isolatedModules — use as const.',
    glossary: [
      { term: 'isolatedModules', longForm: 'per-file transpile', plainDefinition: 'Each file standalone emit unit.', example: 'true for bundlers' },
      { term: 'verbatimModuleSyntax', longForm: 'import type', plainDefinition: 'Type imports must use import type.', example: 'import type { User }' },
      { term: 'const enum', longForm: 'isolated conflict', plainDefinition: 'Inlining needs cross-file — breaks isolated.', example: 'use as const' },
      { term: 'transpileModule', longForm: 'single file API', plainDefinition: 'Babel/esbuild per-file.', example: 'needs isolated rules' },
    ],
    whyMatters: 'Vite fails on const enum. Mixed imports cause runtime import of type-only module.',
    tipTitle: 'Interview trap: import { Type }',
    tipBody: 'verbatimModuleSyntax: interface import must be import type.',
    steps: [{ title: 'isolatedModules true', body: '' }, { title: 'verbatimModuleSyntax', body: 'TS5+' }, { title: 'replace const enum', body: 'as const' }, { title: 'split imports', body: 'type vs value' }],
    diagramTitle: 'per-file transpile',
    diagram: 'flowchart LR\n  F1 --> ES[esbuild]\n  F2 --> ES\n  ISO[isolatedModules] --> ES',
    snippets: [
      snippet('json', 'Vite tsconfig', '{\n  "compilerOptions": {\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "isolatedModules": true,\n    "verbatimModuleSyntax": true,\n    "noEmit": true\n  }\n}', 'Standard frontend config.'),
      snippet('typescript', 'import type', 'import type { User } from "./types";\nimport { createUser } from "./types";', 'Split type/value.'),
      snippet('typescript', 'as const not const enum', 'const Direction = { Up: "up", Down: "down" } as const;\ntype Direction = typeof Direction[keyof typeof Direction];', 'Bundler-safe enum alternative.'),
      snippet('typescript', 'Failure: type import runtime', 'import { Config } from "./config"; // type-only interface — bad emit without verbatim', 'Runtime import empty module.'),
    ],
    compareRows: [['', 'isolatedModules', 'verbatim', 'tsc only'], ['const enum', 'problem', 'problem', 'ok']],
    mistakesBody: 'const enum in Vite. mixed imports. isolatedModules false with Babel.',
    seniorProse: 'eslint consistent-type-imports autofix. Angular esbuild needs isolatedModules.',
    seniorRows: [['verbatim', 'clean emit', 'migration'], ['isolated only', 'partial', 'import mess']],
    seniorWarning: 'never heard isolatedModules. const enum with Vite.',
    interviewTakeaways: ['isolatedModules per-file.', 'verbatimModuleSyntax import type.', 'no const enum bundler.', '60s: bundler per-file. import type. as const. C# whole-program compile.', 'Follow-up: moduleDetection.'],
    commonPitfalls: ['Weak: const enum esbuild.', 'Weak: no import type.', 'Strong: "isolatedModules bundler. verbatim import type. as const."'],
    relatedTopicIds: ['typescript-14-module-resolution-modes', 'typescript-17-strict-compiler-flags', 'typescript-02-enums-and-const-enums'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'esbuild', note: 'per-file strip types.', futureTopicSlug: 'javascript/16-modules-bundling-tooling/bundlers-and-tree-shaking' }, { language: 'typescript', concept: 'Roslyn', note: 'whole program compile.', futureTopicSlug: 'csharp/compiler/roslyn' }],
    officialSources: [{ title: 'isolatedModules', url: 'https://www.typescriptlang.org/tsconfig#isolatedModules' }],
    animationHint: 'flow',
  },
  'project-references': {
    hook: '**Project references** split monorepos — `composite: true`, `references: [{ path }]`, build with `tsc -b` and `.tsbuildinfo` incremental cache.',
    whatIs: 'Child tsconfig **composite** + **declaration**. Parent **references** children. **tsc -b** topological build. **declarationMap** for cross-package go-to-def. paths aliases ≠ references — references define build graph.',
    glossary: [
      { term: 'composite', longForm: 'composite project', plainDefinition: 'Enables references + tsbuildinfo.', example: 'composite true' },
      { term: 'references', longForm: 'project refs', plainDefinition: 'Dependent tsconfig paths.', example: 'references array' },
      { term: 'tsc -b', longForm: 'build mode', plainDefinition: 'Solution build ordered.', example: 'tsc -b --verbose' },
      { term: 'solution tsconfig', longForm: 'root', plainDefinition: 'files [] references all pkgs.', example: 'root tsconfig' },
    ],
    whyMatters: 'Monorepo without refs typechecks all always — slow CI. Nx/Turbo wrap tsc -b. C# solution file analog.',
    tipTitle: 'Interview trap: paths vs references',
    tipBody: 'paths = editor alias; references = build graph + incremental.',
    steps: [{ title: 'composite packages', body: 'declaration true' }, { title: 'references in deps', body: '' }, { title: 'root solution', body: 'files empty' }, { title: 'CI tsc -b', body: 'cache tsbuildinfo' }],
    diagramTitle: 'monorepo refs',
    diagram: 'flowchart BT\n  APP --> LIB\n  APP --> API\n  API --> SHARED',
    snippets: [
      snippet('json', 'composite package', '{\n  "compilerOptions": { "composite": true, "declaration": true, "declarationMap": true, "outDir": "dist" },\n  "include": ["src"]\n}', 'Library composite.'),
      snippet('json', 'app references lib', '{\n  "compilerOptions": { "composite": true },\n  "references": [{ "path": "../shared" }],\n  "include": ["src"]\n}', 'Dependency graph.'),
      snippet('json', 'root solution', '{\n  "files": [],\n  "references": [\n    { "path": "./packages/shared" },\n    { "path": "./apps/web" }\n  ]\n}', 'tsc -b from root.'),
      snippet('bash', 'CI build', 'tsc -b tsconfig.json --pretty false', 'Incremental monorepo typecheck.'),
    ],
    compareRows: [['', 'references', 'paths only', 'C# sln'], ['incremental', 'tsbuildinfo', 'no', 'msbuild cache']],
    mistakesBody: 'composite false on lib. no declaration. paths instead of package imports.',
    seniorProse: 'turbo dependsOn ^build. publish dist .d.ts with types field.',
    seniorRows: [['tsc -b', 'official incremental', 'config overhead'], ['single tsconfig', 'simple small', 'no scale']],
    seniorWarning: 'confuses paths references. no tsc -b.',
    interviewTakeaways: ['composite+references graph.', 'tsc -b incremental.', 'paths≠references.', '60s: composite packages. root solution. declarationMap. C# sln analog.', 'Follow-up: declarationMap.'],
    commonPitfalls: ['Weak: paths only slow CI.', 'Weak: no declaration lib.', 'Strong: "composite+refs+tsc -b. paths editor only."'],
    relatedTopicIds: ['typescript-14-path-mapping', 'typescript-17-ci-typecheck-pipelines', 'typescript-17-eslint-type-aware'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'workspaces', note: 'npm workspaces + refs typecheck.', futureTopicSlug: 'javascript/16-modules-bundling-tooling/monorepos' }, { language: 'typescript', concept: 'solution', note: 'C# .sln.', futureTopicSlug: 'csharp/solutions/project-structure' }],
    officialSources: [{ title: 'Project references', url: 'https://www.typescriptlang.org/docs/handbook/project-references.html' }],
    animationHint: 'flow',
  },
  'eslint-type-aware': {
    hook: '**Type-aware ESLint** uses TS program for rules like **no-floating-promises** — needs parserOptions.project. Complements tsc, does not replace it.',
    whatIs: '@typescript-eslint/parser + **recommendedTypeChecked** preset. **parserOptions.project** or **projectService** (TS 5.8+). Rules: no-floating-promises, no-misused-promises, no-unsafe-assignment. Separate fast vs typed lint in CI.',
    glossary: [
      { term: 'typed lint', longForm: 'type-aware rules', plainDefinition: 'Rules using type checker.', example: 'no-floating-promises' },
      { term: 'parserOptions.project', longForm: 'tsconfig for eslint', plainDefinition: 'Program for rules.', example: 'tsconfig.eslint.json' },
      { term: 'recommended-type-checked', longForm: 'preset', plainDefinition: 'Curated typed rules.', example: 'typescript-eslint preset' },
      { term: 'projectService', longForm: 'TS 5.8', plainDefinition: 'Faster project service API.', example: 'projectService true' },
    ],
    whyMatters: 'tsc misses unawaited promises. Misconfigured project globs false negatives. Senior CI splits lint stages.',
    tipTitle: 'Interview trap: eslint replaces tsc',
    tipBody: 'Run tsc --noEmit AND typed eslint — different jobs.',
    steps: [{ title: 'install typescript-eslint', body: '' }, { title: 'tsconfig.eslint.json', body: 'include tests' }, { title: 'recommendedTypeChecked', body: '' }, { title: 'parallel CI jobs', body: 'fast+typed' }],
    diagramTitle: 'typed eslint',
    diagram: 'flowchart LR\n  SRC --> ESL\n  TSC[TS Program] --> ESL\n  ESL --> RULES',
    snippets: [
      snippet('javascript', 'flat config typed', 'import tseslint from "typescript-eslint";\nexport default tseslint.config(\n  ...tseslint.configs.recommendedTypeChecked,\n  { languageOptions: { parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname } } },\n);', 'Type-checked preset.'),
      snippet('typescript', 'floating promise', 'async function save() { return fetch("/api"); }\nfunction click() { save(); } // eslint error\nasync function fixed() { await save(); }', 'tsc allows — eslint catches.'),
      snippet('typescript', 'misused promises', 'async function ok() { return true; }\nif (ok()) {} // eslint: Promise always truthy\nif (await ok()) {}', 'async in if without await.'),
      snippet('json', 'tsconfig.eslint.json', '{\n  "extends": "./tsconfig.json",\n  "include": ["src", "tests", "*.config.ts"]\n}', 'All linted files in program.'),
    ],
    compareRows: [['', 'tsc', 'typed eslint', 'Roslyn analyzer'], ['floating promise', 'no', 'yes', 'similar']],
    mistakesBody: 'project missing tests. typed lint whole repo no cache. eslint replaces tsc belief.',
    seniorProse: 'turbo lint per package. Roslyn analyzers parallel in C#.',
    seniorRows: [['type-checked', 'async safety', 'CI slow'], ['tsc only', 'fast setup', 'misses floats']],
    seniorWarning: 'eslint typechecks. no parserOptions.project.',
    interviewTakeaways: ['typed eslint uses TS program.', 'no-floating-promises key.', 'project/projectService required.', '60s: typescript-eslint typed rules. tsc+eslint CI. tsconfig.eslint scope. Roslyn parallel.', 'Follow-up: projectService.'],
    commonPitfalls: ['Weak: eslint only no tsc.', 'Weak: project glob missing.', 'Strong: "typed lint needs program. floating promises. tsc still required."'],
    relatedTopicIds: ['typescript-17-strict-compiler-flags', 'typescript-17-ci-typecheck-pipelines', 'typescript-13-promise-and-async-return-types'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'eslint no types', note: 'cannot catch float promise without types.', futureTopicSlug: 'javascript/tooling/eslint' }, { language: 'typescript', concept: 'analyzers', note: 'C# Roslyn rules.', futureTopicSlug: 'csharp/analyzers/roslyn' }],
    officialSources: [{ title: 'typescript-eslint typed linting', url: 'https://typescript-eslint.io/getting-started/typed-linting' }],
    animationHint: 'flow',
  },
  'ci-typecheck-pipelines': {
    hook: '**CI pipelines** run `tsc -b` or `tsc --noEmit`, typed eslint, tests — pin TypeScript version, cache `.tsbuildinfo`, fail-fast before merge.',
    whatIs: 'install → lint → typecheck → test → build. Cache node_modules + tsbuildinfo. **Pin exact typescript** in package.json. Vite build may skip tsc — separate typecheck job required. --pretty false for CI logs.',
    glossary: [
      { term: 'tsc --noEmit', longForm: 'typecheck only', plainDefinition: 'Check without emit.', example: 'npx tsc --noEmit' },
      { term: 'incremental', longForm: 'tsbuildinfo', plainDefinition: 'Cache between CI runs.', example: 'incremental true' },
      { term: 'fail fast', longForm: 'CI gate', plainDefinition: 'Typecheck before e2e.', example: 'block PR on tsc error' },
      { term: 'pinned TS', longForm: 'exact version', plainDefinition: 'CI/local match.', example: '"typescript": "5.7.2"' },
    ],
    whyMatters: 'TS version drift wastes hours. No typecheck merges any. Monorepo without tsc -b cache times out Actions.',
    tipTitle: 'Interview trap: build passes types OK',
    tipBody: 'esbuild transpileOnly / vite may skip types — dedicated tsc job.',
    steps: [{ title: 'pin typescript', body: '' }, { title: 'typecheck script', body: 'tsc -b' }, { title: 'cache tsbuildinfo', body: 'actions cache' }, { title: 'parallel lint+tsc', body: '' }],
    diagramTitle: 'CI stages',
    diagram: 'flowchart LR\n  INSTALL --> LINT\n  INSTALL --> TSC\n  LINT --> TEST\n  TSC --> TEST',
    snippets: [
      snippet('json', 'package scripts', '{\n  "scripts": {\n    "typecheck": "tsc -b --pretty false",\n    "ci": "npm run lint && npm run typecheck && npm test"\n  },\n  "devDependencies": { "typescript": "5.7.2" }\n}', 'CI entry scripts.'),
      snippet('yaml', 'GitHub Actions', 'jobs:\n  typecheck:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: 20, cache: npm }\n      - run: npm ci\n      - run: npm run typecheck', 'Dedicated typecheck job.'),
      snippet('yaml', 'Cache tsbuildinfo', '- uses: actions/cache@v4\n  with:\n    path: "**/*.tsbuildinfo"\n    key: tsc-${{ hashFiles("**/tsconfig*.json") }}', 'Incremental cache.'),
      snippet('typescript', 'Failure: vite only CI', '// vite esbuild transpileOnly — no types checked without tsc job', 'Build ≠ typecheck.'),
    ],
    compareRows: [['stage', 'command', 'catches', 'C#'], ['typecheck', 'tsc -b', 'types', 'dotnet build']],
    mistakesBody: 'no tsc CI. floating typescript ^. no tsbuildinfo cache.',
    seniorProse: 'turbo affected typecheck. husky pre-commit. Node LTS matrix.',
    seniorRows: [['tsc -b CI', 'authoritative', 'maintain refs'], ['IDE only', 'free', 'drift merges']],
    seniorWarning: 'no tsc CI. bundler checks types myth.',
    interviewTakeaways: ['CI explicit tsc.', 'pin TS version.', 'cache tsbuildinfo.', '60s: lint+tsc+test. transpileOnly insufficient. tsc -b monorepo. pin version.', 'Follow-up: turbo affected.'],
    commonPitfalls: ['Weak: vite build only CI.', 'Weak: ^typescript float.', 'Strong: "dedicated tsc job. pin version. cache tsbuildinfo."'],
    relatedTopicIds: ['typescript-17-project-references', 'typescript-17-eslint-type-aware', 'typescript-18-compiler-performance'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'no tsc', note: 'JS may skip — TS must not.', futureTopicSlug: 'javascript/tooling/ci' }, { language: 'typescript', concept: 'dotnet build', note: 'C# always compiles.', futureTopicSlug: 'csharp/ci/github-actions' }],
    officialSources: [{ title: 'TS CI performance', url: 'https://github.com/microsoft/TypeScript/wiki/Performance#ci' }],
    animationHint: 'timeline',
    scenarioTag: 'high-concurrency',
  },
};
