import { snippet } from './build-topic.mjs';

export const m14Topics = {
  'module-resolution-modes': {
    hook: '`moduleResolution` controls import resolution — `nodenext` enforces Node ESM rules and package.json `exports`; `bundler` (TS 5+) matches Vite/esbuild. Wrong mode causes CI failures while IDE works.',
    whatIs: '**node10** ignores exports. **node16/nodenext** enforce extensions, import/require rules, and `package.json` `"type"`. **bundler** allows extensionless imports for webpack/Vite. Pair **`module: nodenext`** with nodenext for Node libraries; **`module: ESNext` + bundler** for frontend apps.',
    glossary: [
      { term: 'nodenext', longForm: 'Node ESM resolution', plainDefinition: 'Respects exports and .js extensions.', example: '"moduleResolution": "nodenext"' },
      { term: 'bundler', longForm: 'bundler resolution', plainDefinition: 'TS 5+ for tools that rewrite imports.', example: '"moduleResolution": "bundler"' },
      { term: 'exports', longForm: 'package.json exports', plainDefinition: 'Conditional subpath map.', example: '"exports": { ".": "./dist/index.js" }' },
      { term: 'ESM', longForm: 'ECMAScript modules', plainDefinition: 'import/export — .mjs or type module.', example: 'import "./file.js"' },
    ],
    whyMatters: 'npm publish with wrong resolution breaks consumers. Monorepos mixing CJS/ESM need nodenext. bundler in libraries hides Node failures.',
    tipTitle: 'Interview trap: extensionless in Node',
    tipBody: 'nodenext requires `import "./file.js"` even when source is file.ts.',
    steps: [{ title: 'Pick runtime', body: 'Node lib → nodenext; Vite → bundler' }, { title: 'Align module', body: 'module + resolution match' }, { title: 'Check type field', body: 'module vs commonjs' }, { title: 'Verify exports', body: 'Subpaths in exports map' }],
    diagramTitle: 'Resolution modes',
    diagram: 'flowchart TD\n  IMP --> MODE{resolution}\n  MODE -->|nodenext| NODE[exports+extensions]\n  MODE -->|bundler| BUN[bundler rewrite]',
    snippets: [
      snippet('typescript', 'nodenext .js import', 'import { helper } from "./utils.js"; // utils.ts source\n// import "./utils" // error under nodenext', '.js extension for relative ESM.'),
      snippet('json', 'package exports', '{\n  "type": "module",\n  "exports": { ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" } }\n}', 'types + import conditions.'),
      snippet('json', 'Vite tsconfig', '{\n  "compilerOptions": {\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "noEmit": true\n  }\n}', 'bundler for Vite apps.'),
      snippet('typescript', 'Failure: node10 ignores exports', 'import { x } from "lib/internal"; // nodenext errors if not in exports', 'Legacy resolution bypasses exports guard.'),
    ],
    compareRows: [['Mode', 'Target', 'Extensions', 'exports'], ['nodenext', 'Node libs', 'Required .js', 'Yes'], ['bundler', 'Vite apps', 'Optional', 'Yes']],
    mistakesBody: 'bundler in published lib. Missing .js under nodenext. Mismatched module settings.',
    seniorProse: 'Dual package hazard. bundler delegates resolution to tool. C# uses assembly refs not package.json.',
    seniorRows: [['nodenext libs', 'Matches Node', 'Verbose imports'], ['bundler apps', 'DX', 'Not for npm lib']],
    seniorWarning: 'Cannot explain nodenext vs bundler. Unaware .js extension rule.',
    interviewTakeaways: ['nodenext = Node ESM + exports.', 'bundler for Vite not libs.', '.js extension under nodenext.', '60s: resolution algorithm. nodenext packages. bundler apps. C# assemblies differ.', 'Follow-up: dual CJS/ESM.'],
    commonPitfalls: ['Weak: bundler in npm package.', 'Weak: no .js extension.', 'Strong: "nodenext Node libs. bundler apps. exports matter."'],
    relatedTopicIds: ['typescript-14-path-mapping', 'typescript-14-typing-javascript-libraries', 'typescript-17-isolated-modules-verbatim'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'Node ESM', note: 'Runtime format TS models.', futureTopicSlug: 'javascript/16-modules-bundling-tooling/esm-vs-commonjs' }, { language: 'typescript', concept: 'assembly refs', note: 'C# compile-time resolution.', futureTopicSlug: 'csharp/assemblies/references' }],
    officialSources: [{ title: 'TS module resolution', url: 'https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-resolution' }],
    animationHint: 'flow',
  },
  'path-mapping': {
    hook: '`paths` and `baseUrl` create import aliases like `@app/*` — compile-time only unless bundler or tsc-alias rewrites emit. Node still sees alias strings at runtime.',
    whatIs: '**paths** maps patterns to folders. TypeScript resolves for checking; **emit keeps alias** unless bundler rewrites. **package.json imports** (#paths) is Node 20+ native alternative. Monorepos prefer **package names** + project references over deep paths.',
    glossary: [
      { term: 'paths', longForm: 'tsconfig paths', plainDefinition: 'Compile-time alias — no emit rewrite.', example: '"@/*": ["src/*"]' },
      { term: 'baseUrl', longForm: 'resolution root', plainDefinition: 'Base for non-relative imports.', example: '"baseUrl": "./src"' },
      { term: 'tsc-alias', longForm: 'post emit rewrite', plainDefinition: 'Rewrites paths in JS for Node.', example: 'tsc && tsc-alias' },
      { term: 'imports field', longForm: 'package.json imports', plainDefinition: 'Runtime-native # alias.', example: '"#internal/*": "./src/*"' },
    ],
    whyMatters: 'CI MODULE_NOT_FOUND when paths work in IDE. Vite alias must mirror tsconfig paths.',
    tipTitle: 'Interview trap: paths rewrite emit',
    tipBody: 'tsc never rewrites path aliases — bundler or tsc-alias required.',
    steps: [{ title: 'Define paths', body: '@app/* → src/*' }, { title: 'Mirror in Vite', body: 'resolve.alias' }, { title: 'Or package imports', body: 'Node # paths' }, { title: 'Monorepo packages', body: '@org/pkg name imports' }],
    diagramTitle: 'paths compile vs runtime',
    diagram: 'flowchart LR\n  SRC["@app/x"] --> TSC[typecheck]\n  TSC --> EMIT["emit @app/x"]\n  EMIT --> BUN[bundler rewrite] or FAIL[Node fail]',
    snippets: [
      snippet('json', 'tsconfig paths', '{\n  "compilerOptions": {\n    "baseUrl": ".",\n    "paths": { "@app/*": ["src/app/*"] }\n  }\n}', 'Alias for imports.'),
      snippet('typescript', 'Alias import', 'import { Button } from "@app/components/Button";', 'Emit unchanged.'),
      snippet('typescript', 'Vite alias', 'export default { resolve: { alias: { "@app": resolve(__dirname, "src/app") } } };', 'Must match tsconfig.'),
      snippet('typescript', 'Failure: Node without rewrite', '// emit: require("@app/foo") → MODULE_NOT_FOUND', 'paths alone insufficient for Node.'),
    ],
    compareRows: [['Mechanism', 'paths', 'package imports', 'C# using'], ['Runtime', 'Needs rewrite', 'Native Node 20+', 'Compile+runtime']],
    mistakesBody: 'paths work in Node without bundler. Mismatched Vite/tsconfig. paths instead of package name in monorepo.',
    seniorProse: 'Nx generates consistent paths. ESLint import resolver reads paths. Prefer @org/lib package imports.',
    seniorRows: [['paths+Vite', 'Great DX', 'Two configs'], ['package imports', 'Runtime native', 'Node version'], ['relative only', 'Simple', 'Deep fragile paths']],
    seniorWarning: 'Says paths rewrites emit. No monorepo package strategy.',
    interviewTakeaways: ['paths compile-time only.', 'Bundler/tsc-alias for Node.', 'package.json imports alternative.', '60s: paths=typecheck. sync Vite. monorepo package names. C# namespaces.', 'Follow-up: project references.'],
    commonPitfalls: ['Weak: paths in tsc output on Node.', 'Weak: Vite/tsconfig mismatch.', 'Strong: "paths typecheck only. bundler rewrite. @org/pkg monorepo."'],
    relatedTopicIds: ['typescript-14-module-resolution-modes', 'typescript-17-project-references', 'typescript-14-typing-javascript-libraries'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'import maps', note: 'Browser runtime resolution.', futureTopicSlug: 'javascript/16-modules-bundling-tooling/module-resolution' }, { language: 'typescript', concept: 'namespaces', note: 'C# using not path-based.', futureTopicSlug: 'csharp/namespaces/using-directives' }],
    officialSources: [{ title: 'TS paths', url: 'https://www.typescriptlang.org/docs/handbook/modules/reference.html#paths' }],
    animationHint: 'flow',
  },
  'ambient-declarations': {
    hook: '**Ambient declarations** (`declare`) describe globals, assets, and env without emitting JS — `declare global`, wildcard `declare module "*.css"`, and `.d.ts` files.',
    whatIs: '**declare** is type-only. **declare global** augments globals from a module file (needs `export {}`). **declare module "*.css"** types asset imports. `.d.ts` files never emit. **@types/*** from DefinitelyTyped for untyped JS libs.',
    glossary: [
      { term: 'ambient', longForm: 'declare', plainDefinition: 'Types without JS output.', example: 'declare const API_URL: string' },
      { term: 'declare global', longForm: 'global augmentation', plainDefinition: 'Extend Window, process, etc.', example: 'declare global { interface Window { ... } }' },
      { term: 'wildcard module', longForm: 'declare module "*.ext"', plainDefinition: 'Type non-TS imports.', example: '*.module.css' },
      { term: 'DefinitelyTyped', longForm: '@types', plainDefinition: 'Community ambient types.', example: '@types/node' },
    ],
    whyMatters: 'process.env and window extensions need types. Vite import.meta.env augmentation. declare vs const — declare describes existing binding.',
    tipTitle: 'Interview trap: declare vs const',
    tipBody: 'declare describes existing runtime value — does not create it.',
    steps: [{ title: 'Find global', body: 'window, process, script tag' }, { title: 'Write .d.ts', body: 'type only' }, { title: 'export {}', body: 'before declare global in .ts' }, { title: 'Include in tsconfig', body: 'types or files' }],
    diagramTitle: 'Ambient vs value',
    diagram: 'flowchart TD\n  D[declare] --> TC[typecheck only]\n  C[const] --> EMIT[emits JS]',
    snippets: [
      snippet('typescript', 'declare global', 'export {};\ndeclare global { interface Window { dataLayer: Array<Record<string, unknown>>; } }\nwindow.dataLayer.push({ event: "pv" });', 'export {} makes module.'),
      snippet('typescript', 'CSS module', 'declare module "*.module.css" {\n  const classes: { readonly [key: string]: string };\n  export default classes;\n}', 'Wildcard asset module.'),
      snippet('typescript', 'ProcessEnv', 'declare namespace NodeJS {\n  interface ProcessEnv { DATABASE_URL: string; NODE_ENV: "development" | "production" | "test"; }\n}', 'Strict env typing.'),
      snippet('typescript', 'Failure: global without export', '// declare global in script mode may fail — use export {} or .d.ts', 'Module context required.'),
    ],
    compareRows: [['declare', 'no emit', 'N/A', 'extern'], ['const', 'emits value', 'creates binding', 'field'], ['.d.ts', 'ambient file', 'N/A', 'reference assembly']],
    mistakesBody: 'declare for values you should implement. global without export {}. conflicting ambients.',
    seniorProse: 'Prefer module augmentation over global pollution. strict env types catch missing CI secrets.',
    seniorRows: [['declare global', 'third-party globals', 'pollution'], ['Zod env', 'runtime+type', 'dep'], ['module augment', 'scoped', 'graph needed']],
    seniorWarning: 'Confuses declare with runtime def. Cannot write declare global.',
    interviewTakeaways: ['declare type-only.', 'global needs export {}.', 'wildcard for assets.', '60s: ambient .d.ts. @types DT. no emit. C# references differ.', 'Follow-up: triple-slash vs import types.'],
    commonPitfalls: ['Weak: declare instead of implement.', 'Weak: global without export {}.', 'Strong: "declare=types only. global augment. wildcard CSS."'],
    relatedTopicIds: ['typescript-14-typing-javascript-libraries', 'typescript-14-declare-module-augmentation', 'typescript-05-declaration-merging'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'globals', note: 'JS globals exist — declare types them.', futureTopicSlug: 'javascript/17-browser-node-runtimes/global-objects-window-process' }, { language: 'typescript', concept: 'reference assembly', note: 'C# metadata reference.', futureTopicSlug: 'csharp/assemblies/metadata' }],
    officialSources: [{ title: 'TS ambient modules', url: 'https://www.typescriptlang.org/docs/handbook/2/modules.html#ambient-modules' }],
    animationHint: 'flow',
  },
  'typing-javascript-libraries': {
    hook: 'Untyped JS libs need **@types/***, bundled `.d.ts`, or hand **`declare module`**. Senior engineers check `package.json` types/exports before installing @types.',
    whatIs: 'Read **.d.ts** for JS APIs. **@types/lodash** from DefinitelyTyped. Internal JS: **allowJs** + JSDoc `@ts-check`. **`declare module "pkg"`** shims untyped npm packages. Modern packages ship types via **exports.types**.',
    glossary: [
      { term: 'DefinitelyTyped', longForm: '@types', plainDefinition: 'Community .d.ts on npm.', example: 'npm i -D @types/react' },
      { term: '.d.ts', longForm: 'declaration file', plainDefinition: 'Type-only API description.', example: 'export function fn(): void' },
      { term: 'allowJs', longForm: 'checkJs', plainDefinition: 'Typecheck .js with JSDoc.', example: '"allowJs": true' },
      { term: 'types field', longForm: 'package.json types', plainDefinition: 'Entry .d.ts for consumers.', example: '"types": "./dist/index.d.ts"' },
    ],
    whyMatters: '@types version skew causes false errors. Enterprise SDKs need hand .d.ts. Publishing requires types in npm package.',
    tipTitle: 'Interview trap: @types vs bundled',
    tipBody: 'Check package types/exports first — @types may be unnecessary or stub.',
    steps: [{ title: 'Check bundled types', body: 'package.json types' }, { title: 'Install @types', body: 'if separate' }, { title: 'declare module shim', body: 'minimal .d.ts' }, { title: 'JSDoc migration', body: 'allowJs gradual' }],
    diagramTitle: 'Typing JS lib',
    diagram: 'flowchart TD\n  LIB --> Q{has d.ts?}\n  Q -->|yes| USE[bundled]\n  Q -->|@types| DT[install]\n  Q -->|no| AUTH[declare module]',
    snippets: [
      snippet('typescript', 'declare module shim', 'declare module "legacy-analytics" {\n  export function track(event: string, props?: Record<string, unknown>): void;\n}\nimport { track } from "legacy-analytics";', 'Shim untyped package.'),
      snippet('typescript', 'JSDoc in .js', '// @ts-check\n/** @param {string} id @returns {Promise<{name:string}>} */\nexport async function loadUser(id) { return fetch(`/u/${id}`).then(r=>r.json()); }', 'Gradual JS typing.'),
      snippet('json', 'Publish types', '{\n  "types": "./dist/index.d.ts",\n  "exports": { ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" } }\n}', 'Consumers get types from package.'),
      snippet('typescript', 'Failure: stale @types', 'import { newMethod } from "foo"; // @types/foo old API', 'Version skew with JS lib.'),
    ],
    compareRows: [['Source', 'bundled', '@types', 'hand shim'], ['Maintainer', 'author', 'DT community', 'your team']],
    mistakesBody: 'any for untyped imports. stale @types. loose declare module.',
    seniorProse: 'attw (Are The Types Wrong) for publish validation. api-extractor for rollup .d.ts.',
    seniorRows: [['bundled types', 'single version', 'author maintains'], ['@types', 'fast', 'skew risk'], ['shim', 'quick', 'no runtime validation']],
    seniorWarning: '@types when package bundles types. Cannot write declare module.',
    interviewTakeaways: ['Check bundled types first.', 'declare module shim.', 'allowJs+JSDoc migration.', '60s: .d.ts describes JS. @types DT. publish types in npm. attw tool.', 'Follow-up: attw.'],
    commonPitfalls: ['Weak: import as any.', 'Weak: @types mismatch.', 'Strong: "bundled first. shim. JSDoc migrate. attw publish."'],
    relatedTopicIds: ['typescript-14-ambient-declarations', 'typescript-14-declare-module-augmentation', 'typescript-14-module-resolution-modes'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'untyped exports', note: 'JS has no static types.', futureTopicSlug: 'javascript/16-modules-bundling-tooling/esm-vs-commonjs' }, { language: 'typescript', concept: 'XML docs', note: 'C# metadata in DLL.', futureTopicSlug: 'csharp/documentation/xml-docs' }],
    officialSources: [{ title: 'DefinitelyTyped', url: 'https://github.com/DefinitelyTyped/DefinitelyTyped' }],
    animationHint: 'flow',
  },
  'declare-module-augmentation': {
    hook: '**Module augmentation** extends third-party types — Express `Request.userId`, Jest custom matchers — via `declare module "exact-name" { interface ... }`.',
    whatIs: '**declare module** merges with existing module declaration. Works on **interfaces** (declaration merging), not type aliases. Must import/reference base module. Side-effect import augmentation file in entry.',
    glossary: [
      { term: 'module augmentation', longForm: 'declare module merge', plainDefinition: 'Add to existing module types.', example: 'declare module "express-serve-static-core"' },
      { term: 'declaration merging', longForm: 'interface merge', plainDefinition: 'Same interface name merges.', example: 'interface User { a } + { b }' },
      { term: 'side-effect import', longForm: 'import "./types"', plainDefinition: 'Loads augmentation into graph.', example: 'import "./express.d.ts"' },
      { term: 'exact module id', longForm: 'resolution string', plainDefinition: 'Must match import resolution.', example: '"express-serve-static-core" not "Express"' },
    ],
    whyMatters: 'Auth middleware req.user typing. Jest matcher extensions. Wrong module string — silent no merge. C# extension methods are runtime.',
    tipTitle: 'Interview trap: augment type alias',
    tipBody: 'type aliases cannot be augmented — interfaces only.',
    steps: [{ title: 'import base module', body: 'activate in graph' }, { title: 'declare module exact id', body: 'match resolution' }, { title: 'extend interface', body: 'inside block' }, { title: 'side-effect import', body: 'app entry' }],
    diagramTitle: 'Augmentation merge',
    diagram: 'flowchart LR\n  ORIG[@types/express] --> AUG[your augment]\n  AUG --> MERGED[Merged Request]',
    snippets: [
      snippet('typescript', 'Express Request', 'import "express-serve-static-core";\ndeclare module "express-serve-static-core" { interface Request { userId?: string; } }\nfunction h(req: import("express").Request) { console.log(req.userId); }', 'Standard Express pattern.'),
      snippet('typescript', 'Jest matchers', 'declare global { namespace jest { interface Matchers<R> { toBeWithinRange(a: number, b: number): R; } } }', 'Custom matcher types.'),
      snippet('typescript', 'Library consumer extend', 'declare module "my-lib" { interface Config { debug?: boolean; } }', 'Ship augmentation for consumers.'),
      snippet('typescript', 'Failure: wrong name', 'declare module "Express" { interface Request { x: string } } // no merge', 'Case/name must match resolution.'),
    ],
    compareRows: [['Augment', 'interface merge compile-time', 'N/A', 'extension methods runtime'], ['type alias', 'cannot augment', 'N/A', 'cannot extend type alias']],
    mistakesBody: 'wrong module string. augment type alias. forget side-effect import.',
    seniorProse: 'Nest reflect-metadata + augmentation. Prefer explicit context type in large teams. type tests for augmentations.',
    seniorRows: [['module augment', 'ecosystem standard', 'silent fail wrong string'], ['wrapper type', 'explicit', 'boilerplate'], ['generic context', 'type-safe', 'refactor handlers']],
    seniorWarning: 'Cannot write Express augment. Tries augment type alias.',
    interviewTakeaways: ['declare module merges interfaces.', 'exact module id string.', 'side-effect import.', '60s: Express Request. interface only. C# extensions runtime.', 'Follow-up: global vs module.'],
    commonPitfalls: ['Weak: wrong module casing.', 'Weak: augment type alias.', 'Strong: "exact module id. interface merge. side-effect import."'],
    relatedTopicIds: ['typescript-14-ambient-declarations', 'typescript-05-declaration-merging', 'typescript-16-reflect-metadata'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'runtime property', note: 'JS adds req.user — TS types it.', futureTopicSlug: 'javascript/09-structural-typing-patterns/duck-typing' }, { language: 'typescript', concept: 'extension methods', note: 'C# runtime dispatch.', futureTopicSlug: 'csharp/classes/extension-methods' }],
    officialSources: [{ title: 'TS module augmentation', url: 'https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation' }],
    animationHint: 'flow',
    scenarioTag: 'auth-token',
  },
};
