import { snippet } from './build-topic.mjs';

export const m15Topics = {
  'branded-and-opaque-types': {
    hook: '**Branded types** add compile-time tags so `UserId` and `OrderId` are both strings at runtime but not interchangeable. Zero runtime cost — C# has nominal types natively.',
    whatIs: 'Brand: `type UserId = string & { readonly [__brand]: unique symbol }`. Factory validates then casts. **Opaque** hides structure — only factory constructs. Brands erase on emit — validation must be in factory.',
    glossary: [
      { term: 'brand', longForm: 'branded type', plainDefinition: 'Phantom tag on primitive.', example: 'string & { __brand: "UserId" }' },
      { term: 'opaque', longForm: 'hidden structure', plainDefinition: 'Consumers cannot see internals.', example: 'Opaque<string, "Token">' },
      { term: 'nominal', longForm: 'nominal typing', plainDefinition: 'TS structural — brands simulate nominal.', example: 'UserId ≠ OrderId' },
      { term: 'phantom', longForm: 'compile-time only', plainDefinition: 'Brand never at runtime.', example: 'erased on emit' },
    ],
    whyMatters: 'Swap user/order IDs causes data bugs — brands catch compile-time. Currency cents vs dollars. UUID vs string.',
    tipTitle: 'Interview trap: brand at runtime',
    tipBody: 'Runtime still plain string — factory must validate.',
    steps: [{ title: 'define brand', body: 'string & unique symbol' }, { title: 'factory', body: 'validate + cast' }, { title: 'API uses brand', body: 'loadUser(id: UserId)' }, { title: 'ban export cast', body: 'as UserId only in factory' }],
    diagramTitle: 'Branded safety',
    diagram: 'flowchart LR\n  RAW[string] --> FACT[UserId()]\n  FACT --> API[loadUser]\n  RAW -.->|blocked| API',
    snippets: [
      snippet('typescript', 'UserId vs OrderId', 'declare const __u: unique symbol;\ndeclare const __o: unique symbol;\ntype UserId = string & { readonly [__u]: never };\ntype OrderId = string & { readonly [__o]: never };\nfunction UserId(v: string): UserId { if (!/^usr_/.test(v)) throw new Error(); return v as UserId; }\nfunction loadUser(id: UserId) {}\nloadUser("ord_1" as OrderId); // error', 'Distinct brands prevent swap.'),
      snippet('typescript', 'Cents branded', 'type Cents = number & { readonly __c: unique symbol };\nfunction Cents(n: number): Cents { if (!Number.isInteger(n)) throw new Error(); return n as Cents; }\nfunction add(a: Cents, b: Cents) { return Cents(a + b); }', 'Integer cents only.'),
      snippet('typescript', 'Opaque helper', 'type Opaque<T, Tag extends string> = T & { readonly __opaque: Tag };\ntype Token = Opaque<string, "Token">;\nfunction createToken(s: string): Token { if (s.length < 32) throw new Error(); return s as Token; }', 'Reusable opaque pattern.'),
      snippet('typescript', 'Failure: cast bypass', 'const id = "hack" as UserId; loadUser(id); // compiles unsafely', 'as UserId without factory defeats brand.'),
    ],
    compareRows: [['', 'Branded', 'Wrapper class', 'C# nominal'], ['Runtime', 'zero', 'object alloc', 'zero']],
    mistakesBody: 'export as Brand casts. over-brand every string.',
    seniorProse: 'zod .brand(). Use for IDs, currency, units. C# record struct has runtime wrapper.',
    seniorRows: [['brand', 'zero cost', 'factory discipline'], ['class wrapper', 'instanceof', 'alloc']],
    seniorWarning: 'Brands at runtime. Cast around factory.',
    interviewTakeaways: ['Brand compile-time zero cost.', 'Factory validates.', 'UserId≠OrderId.', '60s: phantom tag. factory only. erases. C# nominal native.', 'Follow-up: zod brand.'],
    commonPitfalls: ['Weak: as UserId no validation.', 'Weak: brand everything.', 'Strong: "phantom tag. factory entry. zero runtime."'],
    relatedTopicIds: ['typescript-15-recursive-types', 'typescript-15-builder-pattern-typing', 'typescript-02-any-unknown-never'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'plain strings', note: 'JS no brands.', futureTopicSlug: 'javascript/09-structural-typing-patterns/branding-and-symbols' }, { language: 'typescript', concept: 'nominal', note: 'C# Id struct.', futureTopicSlug: 'csharp/types/nominal-typing' }],
    officialSources: [{ title: 'Basarat nominal typing', url: 'https://basarat.gitbook.io/typescript/main-1/nominaltyping' }],
    animationHint: 'compare',
  },
  'recursive-types': {
    hook: '**Recursive types** model JSON trees and ASTs: `type Json = string | Json[] | { [k: string]: Json }`. Compiler depth limits cause TS2589 on deep mapped recursion.',
    whatIs: 'Type references itself. **Json** union canonical. **interface** for trees often cleaner. **Depth-limited** DeepPartial prevents TS2589. Runtime validation still required — types erase.',
    glossary: [
      { term: 'recursive', longForm: 'self-reference', plainDefinition: 'Type includes itself.', example: 'type Tree<T> = { v: T; c: Tree<T>[] }' },
      { term: 'TS2589', longForm: 'excessively deep', plainDefinition: 'Compiler depth limit.', example: 'unbounded mapped recursion' },
      { term: 'Json', longForm: 'JSONValue', plainDefinition: 'Standard recursive JSON type.', example: 'string|number|Json[]|{...}' },
      { term: 'zod lazy', longForm: 'runtime recursive schema', plainDefinition: 'Matches recursive type at boundary.', example: 'z.lazy(() => schema)' },
    ],
    whyMatters: 'API trees, AST, config. DeepPartial<Json> blows budget. Interview JSON + depth question.',
    tipTitle: 'Interview trap: infinite expansion',
    tipBody: 'Unbounded mapped recursion on Json → TS2589 — add depth param.',
    steps: [{ title: 'base + recursive arm', body: 'union self-ref' }, { title: 'interface for trees', body: 'Node { children: Node[] }' }, { title: 'watch depth', body: 'simplify conditionals' }, { title: 'runtime validate', body: 'zod lazy' }],
    diagramTitle: 'Json recursion',
    diagram: 'flowchart TD\n  J --> P[primitives]\n  J --> A[Json[]]\n  J --> O[{string:Json}]\n  A --> J\n  O --> J',
    snippets: [
      snippet('typescript', 'Json type', 'type Json = string | number | boolean | null | Json[] | { [key: string]: Json };\nfunction parseJson(t: string): Json { return JSON.parse(t) as Json; }', 'Canonical pattern — add runtime validator in prod.'),
      snippet('typescript', 'AST interface', 'interface Expr { kind: "lit" | "add"; value?: number; left?: Expr; right?: Expr; }', 'Interface recursive node.'),
      snippet('typescript', 'Depth-limited DeepPartial', 'type DP<T, D extends number = 5> = D extends 0 ? T : T extends object ? { [K in keyof T]?: DP<T[K], [-1,0,1,2,3,4][D]> } : T;', 'Depth counter prevents blow-up.'),
      snippet('typescript', 'Failure: unbounded', '// type Bad<T> = { [K in keyof T]: Bad<T[K]> } on Json → TS2589', 'Need depth or stop at primitives.'),
    ],
    compareRows: [['', 'type recursion', 'interface', 'C# JsonNode'], ['depth limit', 'yes', 'yes', 'runtime tree']],
    mistakesBody: 'unbounded DeepPartial. no runtime JSON validation. mutual recursion with type only.',
    seniorProse: 'zod lazy for runtime. flatten hot path types. F# similar depth issues.',
    seniorRows: [['Json union', 'simple', 'no runtime depth'], ['zod lazy', 'runtime+type', 'bundle']],
    seniorWarning: 'Cannot write Json type. unaware TS2589.',
    interviewTakeaways: ['Json union canonical.', 'TS2589 depth limit.', 'interface for trees.', '60s: recursive Json. depth DeepPartial. zod lazy boundary. C# JsonDocument runtime.', 'Follow-up: zod lazy.'],
    commonPitfalls: ['Weak: infinite DeepPartial.', 'Weak: Json no validator.', 'Strong: "Json union. depth cap. zod lazy."'],
    relatedTopicIds: ['typescript-15-branded-and-opaque-types', 'typescript-12-mapped-types', 'typescript-18-type-complexity-budget'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'nested JSON', note: 'runtime any depth.', futureTopicSlug: 'javascript/types/json' }, { language: 'typescript', concept: 'JsonNode', note: 'C# runtime JSON tree.', futureTopicSlug: 'csharp/types/json' }],
    officialSources: [{ title: 'TS recursive types', url: 'https://www.typescriptlang.org/docs/handbook/2/types-from-types.html#recursive-types' }],
    animationHint: 'flow',
  },
  'builder-pattern-typing': {
    hook: '**Type-state builder** tracks set fields — `build()` only when all required keys present. Generic `Set extends keyof Form` widens per setter.',
    whatIs: 'Each setter returns builder with updated phantom state. **build(this: Builder<Required>)** enforces completeness via `this` parameter. Alternative: fluent `returns this` without compile-time completeness.',
    glossary: [
      { term: 'type-state', longForm: 'progressive builder', plainDefinition: 'Generic tracks set keys.', example: 'FormBuilder<"name"|"email">' },
      { term: 'this parameter', longForm: 'build guard', plainDefinition: 'build only when Set extends Required.', example: 'build(this: B<Required>)' },
      { term: 'phantom state', longForm: 'compile-time only', plainDefinition: 'Not stored at runtime.', example: 'generic Set param' },
      { term: 'fluent', longForm: 'method chaining', plainDefinition: 'returns this for chain.', example: '.name().email().build()' },
    ],
    whyMatters: 'Compile-time half-filled form prevention. ORM/query builders. Interview type-state pattern.',
    tipTitle: 'Interview trap: runtime vs compile complete',
    tipBody: 'Goal: caller cannot call build() until types prove all required keys set.',
    steps: [{ title: 'Required keys union', body: '"name"|"email"' }, { title: 'Builder<Set>', body: 'generic state' }, { title: 'setters widen Set', body: 'Set | "name"' }, { title: 'this on build', body: 'requires Required' }],
    diagramTitle: 'Builder state',
    diagram: 'stateDiagram-v2\n  [*] --> Empty\n  Empty --> HasName: withName\n  HasName --> Done: withEmail\n  Done --> [*]: build',
    snippets: [
      snippet('typescript', 'Type-state builder', 'type Req = "name" | "email";\ninterface F { name: string; email: string; }\nclass B<Set extends keyof F = never> {\n  private d: Partial<F> = {};\n  name(v: string): B<Set | "name"> { this.d.name = v; return this as B<Set | "name">; }\n  email(v: string): B<Set | "email"> { this.d.email = v; return this as B<Set | "email">; }\n  build(this: B<Req>): F { return this.d as F; }\n}\nnew B().name("a").build(); // error\nnew B().name("a").email("b@c.d").build(); // ok', 'this parameter on build.'),
      snippet('typescript', 'Functional sketch', 'type Builder<T, Set extends keyof T = never> = {\n  set<K extends keyof T>(k: K, v: T[K]): Builder<T, Set | K>;\n  build: Set extends keyof T ? () => T : never;\n};', 'build type never until complete.'),
      snippet('typescript', 'Simple fluent', 'class Q { private s = "SELECT *"; where(c: string): this { this.s += ` WHERE ${c}`; return this; } }', 'Chaining without type-state.'),
      snippet('typescript', 'Failure: build always', 'class Bad { build() { return {}; } }', 'No compile-time tracking.'),
    ],
    compareRows: [['', 'type-state', 'runtime if', 'C# fluent'], ['missing field', 'compile error', 'throw', 'throw']],
    mistakesBody: 'over-engineer simple DTOs. build without this typing.',
    seniorProse: 'Kysely SQL builder. plain satisfies for simple forms. C# generators emit builders.',
    seniorRows: [['type-state', 'compile complete', 'hard maintain'], ['zod', 'runtime', 'not build order']],
    seniorWarning: 'Cannot sketch Set generic. no this on build.',
    interviewTakeaways: ['Set generic tracks keys.', 'this on build for Required.', 'phantom compile-only.', '60s: widen Set per setter. this build guard. C# runtime checks often.', 'Follow-up: Kysely.'],
    commonPitfalls: ['Weak: build always callable.', 'Weak: type-state for 2 fields.', 'Strong: "Set generic. this build Required."'],
    relatedTopicIds: ['typescript-15-branded-and-opaque-types', 'typescript-12-conditional-types-basics', 'typescript-09-generic-constraints'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'builder chaining', note: 'JS runtime chain.', futureTopicSlug: 'javascript/09-structural-typing-patterns/factory-and-builder-patterns' }, { language: 'typescript', concept: 'source generators', note: 'C# generated builders.', futureTopicSlug: 'csharp/generators/source-generators' }],
    officialSources: [{ title: 'TS this parameters', url: 'https://www.typescriptlang.org/docs/handbook/2/classes.html#this-parameters' }],
    animationHint: 'flow',
  },
  'type-level-programming-limits': {
    hook: 'Type-level programming has **readability** and **compile-time** costs — senior engineers know when to stop: Zod infer over 40-line conditionals, type budget per directory.',
    whatIs: 'Deep conditionals/recursive mapped types slow tsc and block review. **Type complexity budget**: app=interfaces+zod; shared lib=utilities with review. **extendedDiagnostics** profiles slow files. **satisfies** pragmatic middle.',
    glossary: [
      { term: 'type budget', longForm: 'team convention', plainDefinition: 'Cap on type gymnastics per area.', example: 'no conditionals in features/' },
      { term: 'extendedDiagnostics', longForm: 'tsc perf', plainDefinition: 'Check time per file.', example: 'tsc --extendedDiagnostics' },
      { term: 'infer hell', longForm: 'nested infer', plainDefinition: 'Unreadable infer chains.', example: 'maintainer-only types' },
      { term: 'satisfies', longForm: 'pragmatic check', plainDefinition: 'Validate without widening.', example: 'cfg satisfies Config' },
    ],
    whyMatters: 'One clever types.ts slows IDE for all. On-call cannot read 3-screen errors. Interview: know advanced AND when to refuse.',
    tipTitle: 'Interview trap: clever in prod',
    tipBody: 'Want mechanism knowledge AND judgment to use Zod/codegen instead.',
    steps: [{ title: 'runtime first', body: 'zod infer' }, { title: 'named aliases', body: 'split complex types' }, { title: 'measure compile', body: 'extendedDiagnostics' }, { title: 'review radar', body: 'reject infer hell' }],
    diagramTitle: 'When to stop',
    diagram: 'flowchart TD\n  N[type safety need] --> Q{zod enough?}\n  Q -->|yes| Z[zod infer]\n  Q -->|no| A[advanced types]\n  A --> L{budget?}\n  L -->|no| Z',
    snippets: [
      snippet('typescript', 'Zod over conditional', 'const UserSchema = z.object({ id: z.string().uuid(), email: z.string().email() });\ntype User = z.infer<typeof UserSchema>;\nfunction parseUser(raw: unknown) { return UserSchema.parse(raw); }', 'Single source runtime+type.'),
      snippet('typescript', 'Named aliases', '// Split RouteHead, RouteTail instead of 40-line template recursive type', 'Decompose for compiler and humans.'),
      snippet('bash', 'Profile tsc', 'npx tsc --noEmit --extendedDiagnostics 2>&1 | head -20', 'Find slow files.'),
      snippet('typescript', 'Failure: 80-line type in component', '// components/UserForm.tsx — move to @org/type-utils or simplify', 'Clever types in UI file block team.'),
    ],
    compareRows: [['', 'Zod', 'deep conditional', 'codegen'], ['maintain', 'high', 'low', 'medium'], ['runtime', 'yes', 'no', 'varies']],
    mistakesBody: 'conditional for JSON zod handles. no compile measurement. SO infer paste.',
    seniorProse: 'TYPE_BUDGET in CONTRIBUTING. @org/type-utils package. principal reviews type PRs.',
    seniorRows: [['zod infer', 'default APIs', 'runtime dep'], ['type-utils pkg', 'reuse clever', 'still complex']],
    seniorWarning: 'Only flex types no stop rule. ignores compile time.',
    interviewTakeaways: ['Type cost readability+compile.', 'Zod replaces many conditionals.', 'extendedDiagnostics.', '60s: budget per team. zod boundaries. named aliases. C# generators for codegen.', 'Follow-up: type-fest.'],
    commonPitfalls: ['Weak: 100-line conditional API.', 'Weak: no perf measure.', 'Strong: "zod first. budget. split aliases. codegen heavy."'],
    relatedTopicIds: ['typescript-18-type-complexity-budget', 'typescript-12-conditional-types-basics', 'typescript-15-advanced-patterns-vs-csharp'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'runtime validation', note: 'JS needs runtime always.', futureTopicSlug: 'javascript/09-structural-typing-patterns/runtime-shape-validation' }, { language: 'typescript', concept: 'generators', note: 'C# codegen to readable code.', futureTopicSlug: 'csharp/generators/source-generators' }],
    officialSources: [{ title: 'TS performance authoring', url: 'https://github.com/microsoft/TypeScript/wiki/Performance#authoring-easy-to-compile-code' }],
    animationHint: 'timeline',
  },
  'advanced-patterns-vs-csharp': {
    hook: 'TS **conditional types** and **brands** are compile-only; C# **source generators** and **records** emit runtime code. Map patterns across stacks.',
    whatIs: 'TS types erase — pair with Zod at boundaries. C# generators emit IL + code. Brand ≈ record struct wrapper. DeepPartial type-only — use clone at runtime. OpenAPI single schema for both.',
    glossary: [
      { term: 'source generator', longForm: 'Roslyn generator', plainDefinition: 'Emit C# at compile.', example: '[Generator]' },
      { term: 'type erasure', longForm: 'TS emit', plainDefinition: 'No T in JS.', example: 'brands vanish' },
      { term: 'record struct', longForm: 'C# nominal ID', plainDefinition: 'Thin wrapper with validation.', example: 'record struct UserId(string Value)' },
      { term: 'OpenAPI', longForm: 'shared schema', plainDefinition: 'Codegen TS + C#.', example: 'openapi-typescript + NSwag' },
    ],
    whyMatters: 'Angular + .NET teams duplicate DTOs. Misapply nominal thinking to structural TS. Interview cross-language mapping.',
    tipTitle: 'Interview trap: TS types as runtime',
    tipBody: 'strictNullChecks compile-only — validate at boundaries like C# deserialization still throws.',
    steps: [{ title: 'identify need', body: 'compile vs runtime' }, { title: 'TS types+zod', body: 'boundary' }, { title: 'C# generators', body: 'boilerplate' }, { title: 'OpenAPI', body: 'DRY schema' }],
    diagramTitle: 'TS vs C# metaprogramming',
    diagram: 'flowchart LR\n  subgraph TS\n    T[types] --> E[erased]\n    Z[zod] --> R[runtime]\n  end\n  subgraph CS\n    G[generator] --> IL[CLR code]\n  end',
    snippets: [
      snippet('typescript', 'TS brand', 'type UserId = string & { __b: "UserId" };\nfunction UserId(s: string): UserId { if (!s) throw new Error(); return s as UserId; }', 'Compile tag only.'),
      snippet('csharp', 'C# record', 'public readonly record struct UserId(string Value) {\n  public static UserId Create(string s) => string.IsNullOrEmpty(s) ? throw new ArgumentException() : new UserId(s);\n}', 'Runtime nominal.'),
      snippet('typescript', 'DeepPartial type-only', 'type DeepPartial<T> = { [K in keyof T]?: DeepPartial<T[K]> };\n// runtime: structuredClone or lodash', 'Type utility ≠ runtime object.'),
      snippet('typescript', 'OpenAPI codegen', '// openapi-typescript + NSwag from same api.yaml', 'Shared contract.'),
    ],
    compareRows: [['ID safety', 'brand', 'record struct', 'record struct'], ['partial DTO', 'DeepPartial type', 'init record', 'init'], ['boilerplate', 'conditionals', 'generators', 'generators'], ['runtime', 'zod', 'CLR', 'CLR']],
    mistakesBody: 'DeepPartial without runtime clone. duplicate schemas manually. C# structural confusion.',
    seniorProse: 'protobuf ts-proto + grpc.tools. MediatR vs TS service errors alignment.',
    seniorRows: [['OpenAPI', 'DRY', 'pipeline'], ['TS types only', 'fast', 'no runtime'], ['C# generators', 'runtime', 'build complexity']],
    seniorWarning: 'TS=C# runtime types. no shared schema.',
    interviewTakeaways: ['TS erases — zod boundary.', 'C# generators runtime.', 'brand≈record wrapper.', '60s: structural vs nominal. OpenAPI shared. zod TS. generators C#.', 'Follow-up: protobuf.'],
    commonPitfalls: ['Weak: DeepPartial no runtime.', 'Weak: duplicate DTOs.', 'Strong: "TS compile-only. C# generators runtime. OpenAPI DRY. brands≈records."'],
    relatedTopicIds: ['typescript-15-branded-and-opaque-types', 'typescript-15-type-level-programming-limits', 'typescript-02-basic-types-vs-csharp'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'no static layer', note: 'TS patterns → JS without types.', futureTopicSlug: 'javascript/01-what-is-javascript/types-vs-javascript' }, { language: 'typescript', concept: 'Roslyn', note: 'C# emits real code.', futureTopicSlug: 'csharp/generators/roslyn' }],
    officialSources: [{ title: 'C# source generators', url: 'https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview' }],
    animationHint: 'compare',
  },
};
