import { snippet } from './build-topic.mjs';

export const m16Topics = {
  'stage-3-decorators': {
    hook: '**Stage 3 decorators** (TS 5.0+, TC39) use `(value, context) => value` — replaces experimental 3-arg API. context.kind, context.name, addInitializer for setup.',
    whatIs: 'Disable experimentalDecorators. Decorator receives value + **DecoratorContext**. Class/method/field/accessor targets. **Decorator factories** return decorator. **addInitializer** runs post-construct. No reflect-metadata required for basic metadata — context provides it.',
    glossary: [
      { term: 'Stage 3', longForm: 'standard decorators', plainDefinition: 'TC39 proposal in TS 5.0.', example: '(fn, context) => fn' },
      { term: 'DecoratorContext', longForm: 'context object', plainDefinition: 'kind, name, static, private.', example: 'context.kind === "method"' },
      { term: 'factory', longForm: 'decorator factory', plainDefinition: 'Returns decorator with config.', example: 'Logged("api")' },
      { term: 'addInitializer', longForm: 'post-construct', plainDefinition: 'Callback after instance created.', example: 'context.addInitializer(()=>{})' },
    ],
    whyMatters: 'Angular 19+ path to standard decorators. Migration from legacy. Interview: signature difference.',
    tipTitle: 'Interview trap: legacy vs stage 3',
    tipBody: 'Legacy (target, key, descriptor) vs stage 3 (value, context) — different APIs.',
    steps: [{ title: 'TS 5+ config', body: 'experimentalDecorators false' }, { title: 'write decorator', body: '(value, context)' }, { title: 'factory for opts', body: 'return decorator' }, { title: 'test emit', body: 'stage 3 in output' }],
    diagramTitle: 'Stage 3 apply',
    diagram: 'flowchart TD\n  CLASS --> DEC[@decorator]\n  DEC --> CTX[context]\n  CTX --> OUT[value/initializer]',
    snippets: [
      snippet('typescript', 'Method decorator', 'function logged<T extends (...args: unknown[]) => unknown>(fn: T, ctx: ClassMethodDecoratorContext): T {\n  const name = String(ctx.name);\n  return function (this: unknown, ...args: unknown[]) { console.log(name); return fn.apply(this, args); } as T;\n}\nclass Api { @logged fetch() { return "d"; } }', 'Stage 3 method wrap.'),
      snippet('typescript', 'Factory + addInitializer', 'function Validate(min: number) {\n  return function (_v: unknown, ctx: ClassFieldDecoratorContext) {\n    ctx.addInitializer(function () {\n      const v = (this as Record<string, unknown>)[ctx.name as string];\n      if (typeof v === "number" && v < min) throw new Error("small");\n    });\n  };\n}\nclass C { @Validate(0) accessor timeout = 100; }', 'Field validation via initializer.'),
      snippet('typescript', 'Class decorator', 'function sealed<T extends { new(...a: unknown[]): object }>(ctor: T, ctx: ClassDecoratorContext) {\n  ctx.addInitializer(() => console.log(ctx.name));\n  return ctor;\n}\n@sealed class S {}', 'Class decorator.'),
      snippet('typescript', 'Failure: mixed modes', '// experimentalDecorators true + stage 3 body = errors', 'One decorator system per project.'),
    ],
    compareRows: [['API', '(value,context)', 'N/A', 'attributes'], ['timing', 'class def', 'N/A', 'compile/runtime mix']],
    mistakesBody: 'legacy signature with stage 3 enabled. wrong target kind.',
    seniorProse: 'TC39 spec for context fields. Plan Nest/Angular migration codemods.',
    seniorRows: [['stage 3', 'standard', 'ecosystem migrating'], ['legacy', 'works today', 'deprecated']],
    seniorWarning: 'Same legacy/stage3 signature. cannot write decorator.',
    interviewTakeaways: ['stage 3 (value,context).', 'factories.', 'addInitializer.', '60s: TS5 standard. context fields. legacy different. C# attributes differ.', 'Follow-up: Angular migration.'],
    commonPitfalls: ['Weak: legacy sig stage3 mode.', 'Weak: types as runtime.', 'Strong: "(value,context). factory. addInitializer. migrate experimental."'],
    relatedTopicIds: ['typescript-16-legacy-decorators', 'typescript-16-reflect-metadata', 'typescript-16-decorators-in-frameworks'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'decorators proposal', note: 'JS language feature.', futureTopicSlug: 'javascript/classes/decorators' }, { language: 'typescript', concept: 'attributes', note: 'C# metadata attach.', futureTopicSlug: 'csharp/attributes/custom-attributes' }],
    officialSources: [{ title: 'TS 5.0 decorators', url: 'https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators' }],
    animationHint: 'flow',
  },
  'legacy-decorators': {
    hook: '**Legacy decorators** need `experimentalDecorators: true` — 3-arg `(target, key, descriptor)`. Angular, NestJS, class-validator still use them.',
    whatIs: '**experimentalDecorators** enables pre-standard API. Method decorator mutates **PropertyDescriptor**. **Parameter decorators** legacy-only for DI. **emitDecoratorMetadata** + **reflect-metadata** for design:paramtypes. **useDefineForClassFields: false** often required for Angular @Input.',
    glossary: [
      { term: 'experimentalDecorators', longForm: 'legacy flag', plainDefinition: 'Old decorator implementation.', example: 'true in tsconfig' },
      { term: 'PropertyDescriptor', longForm: 'method descriptor', plainDefinition: 'value/writable/enumerable/configurable.', example: 'descriptor.value = wrapped' },
      { term: 'parameter decorator', longForm: '@Param()', plainDefinition: 'Records param index — DI.', example: 'Nest @Body()' },
      { term: 'emitDecoratorMetadata', longForm: 'design:type emit', plainDefinition: 'Emits metadata for reflect-metadata.', example: 'true with legacy' },
    ],
    whyMatters: 'Production Angular/Nest on legacy today. Wrong tsconfig breaks DI. parameter decorators not in stage 3 yet.',
    tipTitle: 'Interview trap: parameter decorators stage 3',
    tipBody: 'Stage 3 has no parameter decorators — Nest DI relies on legacy.',
    steps: [{ title: 'experimentalDecorators true', body: '' }, { title: 'emitDecoratorMetadata', body: 'if DI' }, { title: 'import reflect-metadata', body: 'entry' }, { title: 'plan migration', body: 'framework version' }],
    diagramTitle: 'Legacy method dec',
    diagram: 'flowchart LR\n  M[@Log] --> D[descriptor.value]\n  D --> W[wrapped fn]',
    snippets: [
      snippet('typescript', 'Legacy method', 'function Log(_t: object, key: string | symbol, d: PropertyDescriptor) {\n  const orig = d.value as (...a: unknown[]) => unknown;\n  d.value = function (...a: unknown[]) { console.log(String(key)); return orig.apply(this, a); };\n}\nclass G { @Log greet() { return "hi"; } }', '3-arg descriptor mutation.'),
      snippet('typescript', 'Parameter decorator', 'function Inject(token: string) {\n  return (target: object, _k: string | symbol | undefined, idx: number) => { /* register idx→token */ };\n}\nclass S { constructor(@Inject("CFG") private c: unknown) {} }', 'DI parameter index.'),
      snippet('json', 'Angular tsconfig', '{\n  "compilerOptions": {\n    "experimentalDecorators": true,\n    "emitDecoratorMetadata": true,\n    "useDefineForClassFields": false\n  }\n}', 'Angular field decorator compat.'),
      snippet('typescript', 'Failure: stage3 in legacy project', '// experimentalDecorators true — stage 3 signature fails', 'One mode per project.'),
    ],
    compareRows: [['', 'legacy 3-arg', 'stage 3', 'C# attributes'], ['param dec', 'yes', 'no', 'rare']],
    mistakesBody: 'useDefineForClassFields true breaks @Input. missing reflect-metadata.',
    seniorProse: 'Angular migration docs. codemod decorator signatures. test DI after tsconfig change.',
    seniorRows: [['stay legacy', 'stable prod', 'debt'], ['migrate stage3', 'standard', 'breaking upgrades']],
    seniorWarning: 'no 3-arg knowledge. param dec in stage3.',
    interviewTakeaways: ['experimentalDecorators=true legacy.', 'emitDecoratorMetadata+reflect-metadata.', 'param dec legacy only.', '60s: legacy descriptor. Nest/Angular today. migrate when supported. useDefineForClassFields.', 'Follow-up: useDefineForClassFields.'],
    commonPitfalls: ['Weak: stage3 in Nest without migration.', 'Weak: no reflect-metadata.', 'Strong: "legacy 3-arg. emitDecoratorMetadata. param DI. migrate later."'],
    relatedTopicIds: ['typescript-16-stage-3-decorators', 'typescript-16-reflect-metadata', 'typescript-16-decorators-in-frameworks'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'babel legacy dec', note: 'Babel old proposal.', futureTopicSlug: 'javascript/tooling/babel-decorators' }, { language: 'typescript', concept: 'DI', note: 'C# constructor injection.', futureTopicSlug: 'csharp/di/dependency-injection' }],
    officialSources: [{ title: 'TS legacy decorators', url: 'https://www.typescriptlang.org/docs/handbook/decorators.html' }],
    animationHint: 'timeline',
  },
  'reflect-metadata': {
    hook: '**reflect-metadata** + **emitDecoratorMetadata** provide design:paramtypes for Nest/Angular DI — `Reflect.getMetadata("design:paramtypes", target)`.',
    whatIs: 'Import `reflect-metadata` once at entry. **emitDecoratorMetadata** emits __metadata calls. **design:paramtypes** = constructor array for params. **Interfaces erase** — use @Inject(token). Generics often become Object.',
    glossary: [
      { term: 'reflect-metadata', longForm: 'polyfill', plainDefinition: 'Reflect.getMetadata API.', example: 'import "reflect-metadata"' },
      { term: 'design:paramtypes', longForm: 'param types', plainDefinition: 'Runtime ctor fns for params.', example: 'Reflect.getMetadata(...)' },
      { term: 'emitDecoratorMetadata', longForm: 'compiler emit', plainDefinition: 'Metadata for decorated decls.', example: 'tsconfig true' },
      { term: 'inject token', longForm: '@Inject()', plainDefinition: 'Interface params need token.', example: '@Inject(USER_REPO)' },
    ],
    whyMatters: 'Nest resolves constructor deps via paramtypes. Interface injection fails without token. Security: metadata not validation.',
    tipTitle: 'Interview trap: interface in constructor',
    tipBody: 'constructor(private repo: IUserRepo) paramtypes useless — @Inject token required.',
    steps: [{ title: 'emitDecoratorMetadata', body: 'true' }, { title: 'import polyfill', body: 'first line main' }, { title: 'decorate class', body: '' }, { title: 'framework reads metadata', body: 'DI container' }],
    diagramTitle: 'Metadata pipeline',
    diagram: 'flowchart LR\n  TS --> EMIT[emitDecoratorMetadata]\n  EMIT --> META[__metadata]\n  META --> RM[reflect-metadata]\n  RM --> DI[Nest DI]',
    snippets: [
      snippet('typescript', 'paramtypes demo', 'import "reflect-metadata";\nclass Repo {}\nclass Service { constructor(private r: Repo) {} }\nconst types = Reflect.getMetadata("design:paramtypes", Service);\nconsole.log(types);', 'Shows metadata keys.'),
      snippet('typescript', 'Inject token', 'const USER_REPO = Symbol("USER_REPO");\ninterface UserRepo { find(id: string): Promise<User>; }\nclass UserService { constructor(@Inject(USER_REPO) private repo: UserRepo) {} }', 'Interface needs token.'),
      snippet('typescript', 'Injectable marker', 'function Injectable() { return <T extends { new(...a: unknown[]): object }>(ctor: T) => ctor; }', 'DI scans ctor metadata.'),
      snippet('typescript', 'Failure: no polyfill', '// Reflect.getMetadata is not a function — import reflect-metadata first', 'Must load before decorated classes.'),
    ],
    compareRows: [['', 'emit metadata', 'stage3 context.metadata', 'C# reflection'], ['interface param', 'erased', 'N/A', 'runtime types for classes']],
    mistakesBody: 'interface injection without token. missing polyfill import. expect generics in metadata.',
    seniorProse: 'Angular inject() reduces some needs. explicit tokens preferred in large codebases.',
    seniorRows: [['reflect-metadata DI', 'framework std', 'magic+erasure'], ['manual @Inject', 'explicit', 'verbose']],
    seniorWarning: 'interfaces in paramtypes. no polyfill knowledge.',
    interviewTakeaways: ['emitDecoratorMetadata emits design:*.', 'import reflect-metadata first.', 'interfaces need @Inject.', '60s: Nest DI metadata. paramtypes ctors. interfaces erased. stage3 evolving.', 'Follow-up: Symbol tokens.'],
    commonPitfalls: ['Weak: interface inject no token.', 'Weak: no polyfill.', 'Strong: "emit+polyfill. paramtypes ctors. @Inject interfaces."'],
    relatedTopicIds: ['typescript-16-legacy-decorators', 'typescript-16-decorators-in-frameworks', 'typescript-14-declare-module-augmentation'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'no native reflection', note: 'polyfill adds Reflect.getMetadata.', futureTopicSlug: 'javascript/classes/metadata' }, { language: 'typescript', concept: 'System.Reflection', note: 'C# full reflection.', futureTopicSlug: 'csharp/reflection/overview' }],
    officialSources: [{ title: 'reflect-metadata', url: 'https://github.com/rbuckton/reflect-metadata' }],
    animationHint: 'stack-heap',
  },
  'decorators-in-frameworks': {
    hook: '**Angular**, **NestJS**, **class-validator** use legacy decorators — @Component, @Injectable, @IsEmail. Runtime validation + DI metadata.',
    whatIs: '@Component → Ivy metadata. Nest @Module/@Controller/@Get wires routes + DI. class-validator decorators register rules read at runtime by ValidationPipe. Need experimentalDecorators + often emitDecoratorMetadata.',
    glossary: [
      { term: '@Component', longForm: 'Angular', plainDefinition: 'template, selector, styles.', example: '@Component({ selector: "app" })' },
      { term: '@Injectable', longForm: 'DI marker', plainDefinition: 'Nest/Angular container.', example: '@Injectable()' },
      { term: 'class-validator', longForm: 'validation dec', plainDefinition: '@IsString on DTO fields.', example: '@IsEmail()' },
      { term: 'ValidationPipe', longForm: 'Nest pipe', plainDefinition: 'Runs class-validator on body.', example: 'useGlobalPipes' },
    ],
    whyMatters: 'Full-stack Angular+Nest interviews. DTO without decorators = no runtime validation. tsconfig wrong = broken DI.',
    tipTitle: 'Interview trap: decorators validate types',
    tipBody: 'class-validator runtime — TS types do not validate HTTP body.',
    steps: [{ title: 'tsconfig legacy', body: 'experimentalDecorators' }, { title: 'reflect-metadata', body: 'Nest entry' }, { title: 'DTO decorators', body: 'class-validator' }, { title: 'ValidationPipe', body: 'global' }],
    diagramTitle: 'Nest request',
    diagram: 'flowchart TD\n  POST --> VP[ValidationPipe]\n  VP --> CV[class-validator]\n  CV --> CTRL[@Controller]',
    snippets: [
      snippet('typescript', 'Nest DTO', 'import { IsEmail, IsString, MinLength } from "class-validator";\nexport class CreateUserDto {\n  @IsString() @MinLength(2) name!: string;\n  @IsEmail() email!: string;\n}\n@Post() create(@Body() dto: CreateUserDto) { return this.users.create(dto); }', 'Runtime validation on DTO.'),
      snippet('typescript', 'Angular component', '@Component({ selector: "user-card", standalone: true, template: `<p>{{user.name}}</p>` })\nexport class UserCard { @Input({ required: true }) user!: User; }', 'Legacy component+Input.'),
      snippet('typescript', 'Nest controller', '@Injectable() export class UsersService { findAll() { return []; } }\n@Controller("users") export class UsersController {\n  constructor(private users: UsersService) {}\n  @Get() list() { return this.users.findAll(); }\n}', 'DI wiring.'),
      snippet('typescript', 'Failure: DTO no decorators', 'export class CreateUserDto { name!: string; }\n// ValidationPipe does nothing without decorators', 'Types ≠ runtime validation.'),
    ],
    compareRows: [['', 'Angular', 'Nest', 'ASP.NET'], ['validation', 'class-validator runtime', 'same', 'DataAnnotations']],
    mistakesBody: 'DTO without decorators. wrong useDefineForClassFields. decorators replace TS checking assumption.',
    seniorProse: 'Zod DTO alternative in Nest debate. ASP.NET [Required] parallel.',
    seniorRows: [['class-validator', 'ecosystem', 'boilerplate'], ['zod pipe', 'inferred types', 'custom integration']],
    seniorWarning: '@IsEmail compile-time. no Nest DI knowledge.',
    interviewTakeaways: ['framework needs experimentalDecorators.', 'class-validator runtime.', 'Nest DI paramtypes+tokens.', '60s: @Component Ivy. @Injectable DI. class-validator DTO. ASP.NET parallel.', 'Follow-up: zod vs class-validator.'],
    commonPitfalls: ['Weak: DTO typed no decorators.', 'Weak: interface Nest inject.', 'Strong: "decorators=runtime+DI. reflect-metadata. TS≠validator."'],
    relatedTopicIds: ['typescript-16-legacy-decorators', 'typescript-16-reflect-metadata', 'typescript-16-stage-3-decorators'],
    jsTsCorrelations: [{ language: 'javascript', concept: 'Angular runtime', note: 'decorators compile to metadata.', futureTopicSlug: 'angular/decorators/component' }, { language: 'typescript', concept: 'DataAnnotations', note: 'C# [Required] parallel.', futureTopicSlug: 'csharp/validation/data-annotations' }],
    officialSources: [{ title: 'Nest validation', url: 'https://docs.nestjs.com/techniques/validation' }, { title: 'Angular components', url: 'https://angular.dev/guide/components' }],
    animationHint: 'flow',
    scenarioTag: 'auth-token',
  },
};
