export const mindmaps = {
  'async-types': {
    moduleId: 'typescript-13-async-types',
    title: 'Async types: Promise, AsyncIterable, and AbortSignal — concept map',
    intro: 'Promise<T> return types, Awaited unwrapping, AsyncIterable streams, AbortSignal cancellation, typed async errors, and C# Task comparison.',
    overviewDiagram: { type: 'mermaid', title: 'Async types learning path', source: 'flowchart LR\n  P["Promise<T>"] --> A["Awaited<T>"]\n  A --> I["AsyncIterable"]\n  I --> AB["AbortSignal"]\n  AB --> E["Error typing"]\n  E --> CS["vs C# Task"]' },
    conceptCards: [
      { id: 'promise-returns', title: 'Promise<T> returns', summary: 'async always returns Promise — annotate public APIs.', example: 'async function load(): Promise<User>', topicSlug: 'promise-and-async-return-types' },
      { id: 'awaited-unwrap', title: 'Awaited<T>', summary: 'Recursively unwrap nested PromiseLike.', example: 'type V = Awaited<ReturnType<typeof fn>>', topicSlug: 'awaited-and-async-utility' },
      { id: 'async-iter', title: 'AsyncIterable', summary: 'for await...of over async generators.', example: 'async function* pages(): AsyncGenerator<T>', topicSlug: 'async-iterable-types' },
      { id: 'abort-signal', title: 'AbortSignal', summary: 'Cancel fetch — distinguish AbortError.', example: 'fetch(url, { signal })', topicSlug: 'abort-signal-typing' },
      { id: 'async-errors', title: 'Typed errors', summary: 'catch unknown — Result unions.', example: 'if (e instanceof Error)', topicSlug: 'async-error-typing' },
      { id: 'csharp-task', title: 'vs C# Task', summary: 'Promise erases; no .Result.', example: 'AbortSignal ↔ CancellationToken', topicSlug: 'async-types-vs-csharp-task' },
    ],
    revisionDiagram: { type: 'mermaid', title: 'Async types revision', source: 'mindmap\n  root((Async Types))\n    Promise\n      async returns Promise\n      PromiseLike\n    Awaited\n      recursive unwrap\n    Streams\n      AsyncIterable\n      async generator\n    Cancel\n      AbortController\n      AbortError\n    Errors\n      unknown catch\n      Result\n    CSharp\n      Task runtime\n      IAsyncEnumerable' },
  },
  'modules-and-declarations': {
    moduleId: 'typescript-14-modules-and-declarations',
    title: 'Module resolution and declaration files — concept map',
    intro: 'nodenext vs bundler, paths aliases, ambient declare, .d.ts authoring, module augmentation.',
    overviewDiagram: { type: 'mermaid', title: 'Modules path', source: 'flowchart LR\n  R[moduleResolution] --> P[paths]\n  P --> A[ambient]\n  A --> D[d.ts]\n  D --> M[augmentation]' },
    conceptCards: [
      { id: 'resolution', title: 'nodenext vs bundler', summary: 'Node .js extensions; Vite bundler mode.', example: '"moduleResolution": "nodenext"', topicSlug: 'module-resolution-modes' },
      { id: 'paths', title: 'paths aliases', summary: 'Compile-time only — bundler rewrites.', example: '"@app/*": ["src/*"]', topicSlug: 'path-mapping' },
      { id: 'ambient', title: 'Ambient declare', summary: 'Type-only globals and assets.', example: 'declare global { ... }', topicSlug: 'ambient-declarations' },
      { id: 'typing-js', title: 'Typing JS libs', summary: '@types or declare module.', example: 'declare module "legacy"', topicSlug: 'typing-javascript-libraries' },
      { id: 'augment', title: 'Module augmentation', summary: 'Extend Express Request.', example: 'declare module "express-serve-static-core"', topicSlug: 'declare-module-augmentation' },
    ],
    revisionDiagram: { type: 'mermaid', title: 'Modules revision', source: 'mindmap\n  root((Modules))\n    Resolution\n      nodenext\n      bundler\n    Paths\n      compile only\n    Ambient\n      declare global\n    TypingLibs\n      @types\n    Augment\n      interface merge' },
  },
  'advanced-type-patterns': {
    moduleId: 'typescript-15-advanced-type-patterns',
    title: 'Advanced type-level patterns — concept map',
    intro: 'Branded types, recursive Json, type-state builders, complexity limits, C# generator comparison.',
    overviewDiagram: { type: 'mermaid', title: 'Advanced patterns', source: 'flowchart LR\n  B[Branded] --> R[Recursive]\n  R --> BL[Builder]\n  BL --> L[Limits]\n  L --> CS[vs C#]' },
    conceptCards: [
      { id: 'branded', title: 'Branded types', summary: 'UserId ≠ OrderId at compile time.', example: 'string & { __brand: unique symbol }', topicSlug: 'branded-and-opaque-types' },
      { id: 'recursive', title: 'Recursive types', summary: 'Json union — watch TS2589.', example: 'type Json = string | Json[] | {...}', topicSlug: 'recursive-types' },
      { id: 'builder', title: 'Type-state builder', summary: 'build() when all keys set.', example: 'Builder<"name"|"email">', topicSlug: 'builder-pattern-typing' },
      { id: 'limits', title: 'Type limits', summary: 'Zod over 40-line conditionals.', example: 'z.infer<typeof Schema>', topicSlug: 'type-level-programming-limits' },
      { id: 'vs-csharp', title: 'vs C# generators', summary: 'TS erases; C# emits runtime.', example: 'brand ≈ record struct', topicSlug: 'advanced-patterns-vs-csharp' },
    ],
    revisionDiagram: { type: 'mermaid', title: 'Advanced revision', source: 'mindmap\n  root((Advanced))\n    Branded\n      phantom tag\n    Recursive\n      Json union\n    Builder\n      type state\n    Limits\n      zod budget\n    CSharp\n      generators' },
  },
  'decorators-and-metadata': {
    moduleId: 'typescript-16-decorators-and-metadata',
    title: 'Decorators and metadata — concept map',
    intro: 'Stage 3 decorators, legacy experimental, reflect-metadata, Angular/NestJS/class-validator.',
    overviewDiagram: { type: 'mermaid', title: 'Decorators path', source: 'flowchart LR\n  S3[Stage 3] --> LEG[Legacy]\n  LEG --> RM[reflect-metadata]\n  RM --> FW[Frameworks]' },
    conceptCards: [
      { id: 'stage3', title: 'Stage 3', summary: '(value, context) API — TS 5+.', example: 'function dec(fn, ctx)', topicSlug: 'stage-3-decorators' },
      { id: 'legacy', title: 'Legacy', summary: 'experimentalDecorators 3-arg.', example: 'descriptor.value wrap', topicSlug: 'legacy-decorators' },
      { id: 'reflect', title: 'reflect-metadata', summary: 'design:paramtypes for DI.', example: 'import "reflect-metadata"', topicSlug: 'reflect-metadata' },
      { id: 'frameworks', title: 'Frameworks', summary: '@Component @Injectable @IsEmail.', example: 'ValidationPipe DTO', topicSlug: 'decorators-in-frameworks' },
    ],
    revisionDiagram: { type: 'mermaid', title: 'Decorators revision', source: 'mindmap\n  root((Decorators))\n    Stage3\n      value context\n    Legacy\n      experimentalDecorators\n    Metadata\n      paramtypes\n    Frameworks\n      Nest Angular' },
  },
  'compiler-options-tooling': {
    moduleId: 'typescript-17-compiler-options-tooling',
    title: 'Compiler options and tooling — concept map',
    intro: 'strict flags, isolatedModules, project references, typed ESLint, CI pipelines.',
    overviewDiagram: { type: 'mermaid', title: 'Tooling path', source: 'flowchart LR\n  ST[strict] --> ISO[isolatedModules]\n  ISO --> PR[references]\n  PR --> ESL[typed ESLint]\n  ESL --> CI[tsc -b]' },
    conceptCards: [
      { id: 'strict', title: 'strict family', summary: 'strictNullChecks compile-only.', example: '"strict": true', topicSlug: 'strict-compiler-flags' },
      { id: 'isolated', title: 'isolatedModules', summary: 'import type for bundlers.', example: 'verbatimModuleSyntax', topicSlug: 'isolated-modules-verbatim' },
      { id: 'refs', title: 'Project references', summary: 'composite + tsc -b.', example: 'references: [{path}]', topicSlug: 'project-references' },
      { id: 'eslint', title: 'Typed ESLint', summary: 'no-floating-promises.', example: 'recommendedTypeChecked', topicSlug: 'eslint-type-aware' },
      { id: 'ci', title: 'CI typecheck', summary: 'Pin TS; cache tsbuildinfo.', example: 'npm run typecheck', topicSlug: 'ci-typecheck-pipelines' },
    ],
    revisionDiagram: { type: 'mermaid', title: 'Tooling revision', source: 'mindmap\n  root((Tooling))\n    Strict\n      null checks\n    Isolated\n      import type\n    References\n      tsc build\n    ESLint\n      float promises\n    CI\n      pin version' },
  },
  'ts-recap-performance': {
    moduleId: 'typescript-18-ts-recap-performance',
    title: 'TS recap and performance — concept map',
    intro: 'TS 4.x–5.x map, compiler perf, type budget, review radar, senior challenges.',
    overviewDiagram: { type: 'mermaid', title: 'Recap path', source: 'flowchart LR\n  V[Versions] --> PERF[Perf]\n  PERF --> BUD[Budget]\n  BUD --> RADAR[Radar]\n  RADAR --> CH[Challenges]' },
    conceptCards: [
      { id: 'versions', title: 'Version map', summary: '4.9 satisfies; 5.0 decorators.', example: 'pin typescript version', topicSlug: 'typescript-version-map' },
      { id: 'perf', title: 'Compiler perf', summary: 'skipLibCheck + incremental.', example: 'tsc --extendedDiagnostics', topicSlug: 'compiler-performance' },
      { id: 'budget', title: 'Type budget', summary: 'App=simple; lib=advanced.', example: 'CONTRIBUTING tiers', topicSlug: 'type-complexity-budget' },
      { id: 'radar', title: 'Review radar', summary: 'any, as on json, float promise.', example: 'unknown + zod', topicSlug: 'code-review-radar' },
      { id: 'challenges', title: 'Type challenges', summary: 'DeepPartial, EventMap — zod in prod.', example: 'Parameters<EventHandlers>', topicSlug: 'senior-type-challenges' },
    ],
    revisionDiagram: { type: 'mermaid', title: 'Recap revision', source: 'mindmap\n  root((Recap))\n    Versions\n      satisfies\n      decorators 5\n    Perf\n      skipLibCheck\n    Budget\n      zod boundaries\n    Radar\n      no any json\n    Challenges\n      DeepPartial\n      EventMap' },
  },
};
